title: "Prateek Shrivastava"
description: "AI, Analytics & Supply Chain"
baseurl: "/mywebsite" # 👈 This is critical
url: "https://prateek0489.github.io"

# Optional: Analytics, Author, Social
author:
  name: "Prateek Shrivastava"
  email: "prateek.ietdavv@gmail.com"
