title: "Prateek Shrivastava"
description: "AI, Analytics & Supply Chain | Speaker | Writer"
url: "https://prateekshrivastava.github.io"
author:
  name: "Prateek Shrivastava"
  email: prateek@ietdavv.com
  avatar: /assets/images/prateek.jpg
