title: "Prateek Shrivastava"
description: "AI | Analytics | Supply Chain"
baseurl: ""  # 👈 Custom domain = root deployment
url: "https://pshrivastava.com"
theme: jekyll-theme-primer

nav:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Media"
    url: "/media/"
  - title: "Blog"
    url: "/blog/"
